"""add hints table

Revision ID: ce328111db67
Revises: 495ed6a14d86
Create Date: 2026-03-29 22:49:26.854053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ce328111db67'
down_revision: Union[str, Sequence[str], None] = '495ed6a14d86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hints_id'), table_name='hints')
    op.drop_table('hints')
    op.drop_index(op.f('ix_evaluation_results_id'), table_name='evaluation_results')
    op.drop_table('evaluation_results')
    op.drop_index(op.f('ix_submissions_id'), table_name='submissions')
    op.drop_table('submissions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submissions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('assignment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('language', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('code', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('final_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('attempt_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('submitted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], name=op.f('submissions_assignment_id_fkey')),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('submissions_student_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('submissions_pkey'))
    )
    op.create_index(op.f('ix_submissions_id'), 'submissions', ['id'], unique=False)
    op.create_table('evaluation_results',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('submission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('requirement_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('testcase_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('actual_output', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('execution_time_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('memory_used_mb', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('points_earned', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], name=op.f('evaluation_results_requirement_id_fkey')),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], name=op.f('evaluation_results_submission_id_fkey')),
    sa.ForeignKeyConstraint(['testcase_id'], ['test_cases.id'], name=op.f('evaluation_results_testcase_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('evaluation_results_pkey'))
    )
    op.create_index(op.f('ix_evaluation_results_id'), 'evaluation_results', ['id'], unique=False)
    op.create_table('hints',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('submission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('requirement_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('hint_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], name=op.f('hints_requirement_id_fkey')),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('hints_student_id_fkey')),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], name=op.f('hints_submission_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('hints_pkey'))
    )
    op.create_index(op.f('ix_hints_id'), 'hints', ['id'], unique=False)
    # ### end Alembic commands ###
